const PRODUCT_TYPE = {
  SHOES: 'SHOES',
  FURNITURE: 'FURNITURE',
  CLOTHES: 'CLOTHES',
  KITCHEN_APPLIANCE: 'KITCHEN_APPLIANCE',
};

const GENDER = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNISEX: 'UNISEX',
};

const SHOE_MATERIAL = {
  LEATHER: 'LEATHER',
  CONVERSE: 'CONVERSE',
  SNEAKERS: 'SNEAKERS',
};

const FURNITURE_TYPE = {
  BED: 'BED',
  SOFAS: 'SOFAS',
  DINING_SET: 'DINING_SET',
  DINING_TABLE: 'DINING_TABLE',
  DINING_CHAIR: 'DINING_CHAIR',
  HOME_OTHER: 'HOME_OTHER',
  OFFICE_CHAIR: 'OFFICE_CHAIR',
  BOARDROOM_TABLE: 'BOARDROOM_TABLE',
  WORKSTATION: 'WORKSTATION',
  OFFICE_SOFA: 'OFFICE_SOFA',
  OFFICE_DESK: 'OFFICE_DESK',
  OFFICE_OTHER: 'OFFICE_OTHER',
};

const FURNITURE_CATEGORY = {
  HOME: 'HOME',
  OFFICE: 'OFFICE',
};

const FURNITURE_MATERIAL = {
  WOOD: 'WOOD',
  PLASTIC: 'PLASTIC',
  METAL: 'METAL',
};

const CLOTHES_TYPE = {
  SHIRT: 'SHIRT',
  T_SHIRT: 'T_SHIRT',
  DRESS: 'DRESS',
  SKIRT: 'SKIRT',
  SHORT: 'SHORT',
  TROUSER: 'TROUSER',
  JACKET: 'JACKET',
  VEST: 'VEST',
  SWEATERS: 'SWEATERS',
};

const CLOTHES_MATERIAL = {
  COTTON: 'COTTON',
  WOOL: 'WOOL',
  POLYESTER: 'POLYESTER',
};

const KITCHEN_APPLIANCE_FUNCTION = {
  CUTTING: 'CUTTING',
  SERVING: 'SERVING',
  COOKING: 'COOKING',
  OTHER: 'OTHER',
};

const ROLE = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

const PAYMENT_METHOD = {
  MPESA: 'MPESA',
  STRIPE: 'STRIPE',
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

const DISCOUNT_TYPE = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED',
};

// Helper to get furniture category from furniture type
const getFurnitureCategory = (furnitureType) => {
  const homeTypes = [
    FURNITURE_TYPE.BED,
    FURNITURE_TYPE.SOFAS,
    FURNITURE_TYPE.DINING_SET,
    FURNITURE_TYPE.DINING_TABLE,
    FURNITURE_TYPE.DINING_CHAIR,
    FURNITURE_TYPE.HOME_OTHER,
  ];
  
  return homeTypes.includes(furnitureType) 
    ? FURNITURE_CATEGORY.HOME 
    : FURNITURE_CATEGORY.OFFICE;
};

module.exports = {
  PRODUCT_TYPE,
  GENDER,
  SHOE_MATERIAL,
  FURNITURE_TYPE,
  FURNITURE_CATEGORY,
  FURNITURE_MATERIAL,
  CLOTHES_TYPE,
  CLOTHES_MATERIAL,
  KITCHEN_APPLIANCE_FUNCTION,
  ROLE,
  PAYMENT_STATUS,
  PAYMENT_METHOD,
  ORDER_STATUS,
  DISCOUNT_TYPE,
  getFurnitureCategory,
};
